### ISSUE TITLE
Support matrix mode

### ISSUE THREAD

**Issue by jankapunkt** [meteor-actions/install#1]
Since Meteor 2.3 things are breaking so we often need to test against multiple versions, for example: ['1.9', '2.3']`.

**Comment by make-github-pseudonymous-again** [comment]
I understand your request. But is it not solved in a more elegant way by running tests on two branches each with its own meteor version? Is there a valid use case where the same code state is deployed with different versions of meteor?

NB: For anyone new to this, the current implementation picks up the meteor version from `.meteor/release`: https://github.com/meteor-actions/install/blob/adc00f1000fa07db986f2dd71a1f03a678b1f8f6/action.yml#L11

**Comment by jankapunkt** [comment]
When testing packages we need to test the same codebase against multiple meteor versions and we often use a Meteor project as test proxy because otherwise code coverage would not work correctly or headless client tests would be hard pain.

**Comment by make-github-pseudonymous-again** [comment]
OK. I guess it's easier to setup a matrix strategy than to maintain multiple branches. What would be sufficient? A `with` variable key for the meteor version (that if absent defaults to whatever is inside `.meteor/release`). Then you can wrap this action with a job matrix strategy (exactly like https://github.com/meteorengineer/setup-meteor#usage)?

**Comment by make-github-pseudonymous-again** [comment]
Wait a minute! What exactly does it mean to run multiple versions of Meteor on the same codebase? What about the meteor package versions? Do you mean just the version of the meteor executable?

**Comment by jankapunkt** [comment]
Yes, the Meteor release version can be different from the package version

**Comment by make-github-pseudonymous-again** [comment]
So you just want to specify *version* used here

https://github.com/meteor-actions/install/blob/adc00f1000fa07db986f2dd71a1f03a678b1f8f6/action.yml#L14-L24

and here

https://github.com/meteor-actions/install/blob/adc00f1000fa07db986f2dd71a1f03a678b1f8f6/action.yml#L26-L29

? The rest stays the same?

**Comment by make-github-pseudonymous-again** [comment]
@jankapunkt Do you have an answer to my last post?

**Comment by jankapunkt** [comment]
I am currently doing it like so:

```yaml
jobs:
  unittest:
    name: unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteor: ['1.8.1', '2.3']
    steps:
       - name: Checkout
         uses: actions/checkout@v2 

       - name: Setup meteor ${{ matrix.meteor }}
         uses: meteorengineer/setup-meteor@v1
         with:
           meteor-release: ${{ matrix.meteor }}
```

Caching etc excluded

**Comment by jankapunkt** [comment]
So yes specifying he version is what we need to test for multiple meteor releases

**Comment by make-github-pseudonymous-again** [comment]
@jankapunkt I just released a new version that should allow you to do what you described.

```yaml
jobs:
  unittest:
    name: unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteor: ['1.8.1', '2.3']
    steps:
       - name: Checkout
         uses: actions/checkout@v2 

       - name: Setup meteor ${{ matrix.meteor }}
         uses: meteor-actions/install@v2
         with:
           executable_version: ${{ matrix.meteor }}
```
Note that `executable_version` defaults to `local` which sets the version according to the contents of `.meteor/release`.
You can also specify `latest` which would set the version to the latest Meteor release.

I have decoupled `.meteor/local` caching from the install action so if you want to cache builds your should use

```yaml
jobs:
  unittest:
    name: unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteor: ['1.8.1', '2.3']
    steps:
       - name: Checkout
         uses: actions/checkout@v2 

       - name: Setup meteor ${{ matrix.meteor }}
         uses: meteor-actions/install@v2
         with:
           executable_version: ${{ matrix.meteor }}

       - uses: meteor-actions/cache-build@v2
         with:
           key: unittest
```

The cache key allows to have distinct build caches for different builds (in case of a cache-miss it can still restore from a distinct build, but distinct builds will not overwrite each-others caches). It default to `default`.
